# -*- coding: utf-8 -*-
"""Candidate segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laUMNWCERMJUOAhSMjzS_qDDy0Ngs4yO
"""

!pip install streamlit

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

np.random.seed(42)
high = pd.DataFrame({
    "skills": np.random.randint(12, 20, 400),
    "experience": np.random.randint(4, 10, 400),
    "projects": np.random.randint(4, 8, 400),
    "gpa": np.random.uniform(8.0, 9.5, 400)
})

medium = pd.DataFrame({
    "skills": np.random.randint(6, 12, 400),
    "experience": np.random.randint(2, 5, 400),
    "projects": np.random.randint(2, 4, 400),
    "gpa": np.random.uniform(6.5, 8.0, 400)
})

low = pd.DataFrame({
    "skills": np.random.randint(1, 6, 400),
    "experience": np.random.randint(0, 2, 400),
    "projects": np.random.randint(0, 2, 400),
    "gpa": np.random.uniform(5.0, 6.5, 400)
})

df = pd.concat([high, medium, low], ignore_index=True)

X = df[['skills', 'experience', 'projects', 'gpa']]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X_scaled)
df['cluster'] = clusters
df.head()
df['cluster'].value_counts()
df.groupby('cluster').mean()

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

df['pca1'] = X_pca[:, 0]
df['pca2'] = X_pca[:, 1]
print("Explained variance ratio:", pca.explained_variance_ratio_)
print("Total variance explained:", pca.explained_variance_ratio_.sum())

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x='pca1',
    y='pca2',
    hue='cluster',
    data=df,
    palette='Set2'
)

plt.title("PCA Visualization of 3 Candidate Clusters")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend(title="Cluster")
plt.show()

centers_pca = pca.transform(kmeans.cluster_centers_)

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x='pca1',
    y='pca2',
    hue='cluster',
    data=df,
    palette='Set2'
)

plt.scatter(
    centers_pca[:, 0],
    centers_pca[:, 1],
    c='black',
    s=200,
    marker='X',
    label='Centroids'
)

plt.title("PCA Visualization with Cluster Centroids")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend()
plt.show()

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

st.title("Candidate Segmentation App")
st.write("This app groups candidates using unsupervised learning (KMeans).")
skills = st.slider("Number of Skills", 0, 20, 5)
experience = st.slider("Years of Experience", 0, 10, 1)
projects = st.slider("Number of Projects", 0, 10, 1)
gpa = st.slider("GPA", 0.0, 10.0, 7.0)
user_data = pd.DataFrame([{
    "skills": skills,
    "experience": experience,
    "projects": projects,
    "gpa": gpa
}])
user_scaled = scaler.transform(user_data)
user_cluster = kmeans.predict(user_scaled)[0]
cluster_labels = {
    0: "Low Potential",
    1: "High Potential (Experienced)",
    2: "High Potential (Skill-Focused)"
}

st.subheader("Result")
st.write(f"You belong to: **{cluster_labels[user_cluster]}**")
fig, ax = plt.subplots(figsize=(6, 4))
sns.scatterplot(
    x=df['pca1'],
    y=df['pca2'],
    hue=df['cluster'],
    palette='Set2',
    ax=ax
)
user_pca = pca.transform(user_scaled)
ax.scatter(
    user_pca[:, 0],
    user_pca[:, 1],
    color='black',
    s=200,
    marker='X',
    label='You'
)

ax.set_title("Your Position in Candidate Clusters")
ax.legend()

st.pyplot(fig)